name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  binary:
    name: Publish binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This should work with only the `include`s, but it currently doesn't because of this bug:
        # https://github.community/t5/How-to-use-Git-and-GitHub/GitHub-Actions-Matrix-options-dont-work-as-documented/td-p/29558
        target: [x86_64-osx, x86_64-unknown-linux-musl, armv7-unknown-linux-musleabihf, x86_64-pc-windows-msvc]
        include:
          - os: macos-latest
            target: x86_64-osx
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf

    steps:
      - name: Install libssl-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install libssl-dev

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - uses: actions/checkout@v1
      - name: Build
        run: ci/action.sh release ${{ matrix.target }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/tar/cocogitto.tar.gz
          tag: ${{ github.ref }}
          asset_name: cocogitto-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}.tar.gz
